create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  distance integer not null check (distance >= 0),
  enemies_killed integer not null default 0 check (enemies_killed >= 0),
  bullets_fired jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  rating integer not null check (rating between 1 and 5),
  comment text not null check (char_length(comment) between 1 and 2000),
  created_at timestamptz not null default now()
);

create table if not exists public.updates (
  id bigint generated by default as identity primary key,
  text text not null check (char_length(text) between 1 and 5000),
  created_at timestamptz not null default now()
);

create index if not exists scores_distance_desc_idx on public.scores (distance desc);
create index if not exists scores_user_id_idx on public.scores (user_id);
create index if not exists reviews_created_at_idx on public.reviews (created_at desc);
create index if not exists updates_created_at_idx on public.updates (created_at desc);

alter table public.scores enable row level security;
alter table public.reviews enable row level security;
alter table public.updates enable row level security;

create policy "Scores are publicly readable" on public.scores for select to anon, authenticated using (true);
create policy "Users insert their own scores" on public.scores for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Reviews are publicly readable" on public.reviews for select to anon, authenticated using (true);
create policy "Users insert their own reviews" on public.reviews for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Updates are publicly readable" on public.updates for select to anon, authenticated using (true);
create policy "Admin posts updates" on public.updates for insert to authenticated
with check ((select auth.jwt() ->> 'email') = 'asianthejason@gmail.com');

grant select on public.scores, public.reviews, public.updates to anon, authenticated;
grant insert on public.scores, public.reviews, public.updates to authenticated;
grant usage, select on all sequences in schema public to authenticated;
