create table if not exists public.signal_bastion_scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 80),
  waves integer not null check (waves >= 0),
  enemies_defeated integer not null default 0 check (enemies_defeated >= 0),
  created_at timestamptz not null default now()
);

create index if not exists signal_bastion_scores_rank_idx
  on public.signal_bastion_scores (waves desc, enemies_defeated desc);

alter table public.signal_bastion_scores enable row level security;
create policy "Signal Bastion scores are publicly readable" on public.signal_bastion_scores for select to anon, authenticated using (true);
create policy "Players insert their own Signal Bastion scores" on public.signal_bastion_scores for insert to authenticated with check ((select auth.uid()) = user_id);
grant select on public.signal_bastion_scores to anon, authenticated;
grant insert on public.signal_bastion_scores to authenticated;
grant usage, select on all sequences in schema public to authenticated;
